### ISSUE TITLE
Scripts should not be in index.html

### ISSUE THREAD

**Issue by kenchangh** [anonoz/takeurtime#1]
Yo, your blog's follower here. :smile: 

From your README,

> To deliver the fastest app loading experience (Forget bout the PDFs, we can deal with them later), I put all the CSS and JavaScript into index.html. I know this is insane, but this is some extreme way to counter extra handshakes and latencies.

Well, I'm not a PHP person but surely I can say something about Javascript.

I think it's the wrong thinking you're having. Having it as an external script, it will be cached and the next time it loads, it will be a lot faster. Having a fat chunk of JS to load every **single** time is much slower.

**Comment by anonoz** [comment]
@maverick97  Except the app is explicitly cached, try loading the app without Internet connection.

Anyway thanks for dropping by!

**Comment by kenchangh** [comment]
Hmm, I see, okay.

Enjoy your works! TechinKL especially. It was the reason I went to AngelHack lolol.

**Comment by anonoz** [comment]
@maverick97 Dude you actually used techinkl? I thought no one uses it and was ready to scrap it!

**Comment by kenchangh** [comment]
Well, you're wrong. :P
